const productRoute = "/products";
const productExtension = "png";
export const products = [
  {
    id: "1",
    name: "Laptop",
    description: "Powerful laptop for all your computing needs.",
    price: 999.99,
    wasPrice: 1099.99,
    imageUrl: `${productRoute}/product-1.${productExtension}`,
  },
  {
    id: "2",
    name: "Smartphone",
    description: "High-performance smartphone with the latest features.",
    price: 599.99,
    wasPrice: 699.99,
    imageUrl: `${productRoute}/product-2.${productExtension}`,
  },
  {
    id: "3",
    name: "Tablet",
    description: "Sleek and portable tablet for on-the-go productivity.",
    price: 399.99,
    wasPrice: 449.99,
    imageUrl: `${productRoute}/product-3.${productExtension}`,
  },
  {
    id: "4",
    name: "Gaming Console",
    description: "Next-gen gaming console for immersive gaming experiences.",
    price: 499.99,
    wasPrice: 599.99,
    imageUrl: `${productRoute}/product-4.${productExtension}`,
  },
  {
    id: "5",
    name: "Desktop Computer",
    description: "High-end desktop computer for professional use.",
    price: 1499.99,
    wasPrice: 1599.99,
    imageUrl: `${productRoute}/product-5.${productExtension}`,
  },
  {
    id: "6",
    name: "Wireless Headphones",
    description: "Premium wireless headphones with noise-cancellation.",
    price: 199.99,
    wasPrice: 229.99,
    imageUrl: `${productRoute}/product-6.${productExtension}`,
  },
  {
    id: "7",
    name: "4K Smart TV",
    description: "Ultra-high-definition smart TV for a cinematic experience.",
    price: 799.99,
    wasPrice: 899.99,
    imageUrl: `${productRoute}/product-7.${productExtension}`,
  },
  {
    id: "8",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse for comfortable navigation.",
    price: 29.99,
    wasPrice: 39.99,
    imageUrl: `${productRoute}/product-8.${productExtension}`,
  },
  {
    id: "9",
    name: "External Hard Drive",
    description: "Large-capacity external hard drive for data storage.",
    price: 129.99,
    wasPrice: 149.99,
    imageUrl: `${productRoute}/product-9.${productExtension}`,
  },
  {
    id: "10",
    name: "Smart Speaker",
    description: "Voice-controlled smart speaker with AI assistant.",
    price: 79.99,
    wasPrice: 89.99,
    imageUrl: `${productRoute}/product-10.${productExtension}`,
  },
];